export const languageCodes: Record<string, string[]> = {
	Abkhazian: ['abk', 'ab'],
	Adangme: ['ada'],
	'Adyghe; Adygei': ['ady'],
	'Afro-Asiatic languages': ['afa'],
	Afrihili: ['afh'],
	Afrikaans: ['afr', 'af'],
	Akkadian: ['akk'],
	Albanian: ['alb', 'sqi', 'sq'],
	'Algonquian languages': ['alg'],
	'Southern Altai': ['alt'],
	Amharic: ['amh', 'am'],
	'English, Old (ca.450-1100)': ['ang'],
	'Apache languages': ['apa'],
	'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)': ['arc'],
	Aragonese: ['arg', 'an'],
	Armenian: ['arm', 'hye', 'hy'],
	'Mapudungun; Mapuche': ['arn'],
	Arapaho: ['arp'],
	'Artificial languages': ['art'],
	Assamese: ['asm', 'as'],
	'Asturian; Bable; Leonese; Asturleonese': ['ast'],
	'Athapascan languages': ['ath'],
	'Australian languages': ['aus'],
	Avestan: ['ave', 'ae'],
	Azerbaijani: ['aze', 'az'],
	'Banda languages': ['bad'],
	'Bamileke languages': ['bai'],
	Bashkir: ['bak', 'ba'],
	Baluchi: ['bal'],
	Bambara: ['bam', 'bm'],
	Balinese: ['ban'],
	'Baltic languages': ['bat'],
	'Beja; Bedawiyet': ['bej'],
	Belarusian: ['bel', 'be'],
	Bengali: ['ben', 'bn'],
	'Berber languages': ['ber'],
	Bhojpuri: ['bho'],
	'Bihari languages': ['bih'],
	'Bini; Edo': ['bin'],
	Bislama: ['bis', 'bi'],
	Siksika: ['bla'],
	'Bantu languages': ['bnt'],
	Bosnian: ['bos', 'bs'],
	'Batak languages': ['btk'],
	Buriat: ['bua'],
	Bulgarian: ['bul', 'bg'],
	Burmese: ['bur', 'mya', 'my'],
	'Blin; Bilin': ['byn'],
	'Central American Indian languages': ['cai'],
	'Galibi Carib': ['car'],
	'Catalan; Valencian': ['cat', 'ca'],
	'Caucasian languages': ['cau'],
	Cebuano: ['ceb'],
	'Celtic languages': ['cel'],
	Chamorro: ['cha', 'ch'],
	Chibcha: ['chb'],
	Chechen: ['che', 'ce'],
	Chagatai: ['chg'],
	Chinese: ['chi', 'zho', 'zh'],
	'Chinook jargon': ['chn'],
	Choctaw: ['cho'],
	'Chipewyan; Dene Suline': ['chp'],
	Cherokee: ['chr'],
	'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic': ['chu', 'cu'],
	Chuvash: ['chv', 'cv'],
	Cheyenne: ['chy'],
	'Chamic languages': ['cmc'],
	Montenegrin: ['cnr'],
	Cornish: ['cor', 'kw'],
	'Creoles and pidgins, English based': ['cpe'],
	'Creoles and pidgins, French-based': ['cpf'],
	'Creoles and pidgins, Portuguese-based': ['cpp'],
	'Crimean Tatar; Crimean Turkish': ['crh'],
	'Creoles and pidgins': ['crp'],
	Kashubian: ['csb'],
	'Cushitic languages': ['cus'],
	'Land Dayak languages': ['day'],
	Delaware: ['del'],
	'Slave (Athapascan)': ['den'],
	'Tlicho; Dogrib': ['dgr'],
	'Divehi; Dhivehi; Maldivian': ['div', 'dv'],
	'Dravidian languages': ['dra'],
	'Lower Sorbian': ['dsb'],
	'Dutch, Middle (ca.1050-1350)': ['dum'],
	'Dutch; Flemish': ['dut', 'nld', 'nl'],
	Dzongkha: ['dzo', 'dz'],
	'Egyptian (Ancient)': ['egy'],
	Elamite: ['elx'],
	English: ['eng', 'en'],
	'English, Middle (1100-1500)': ['enm'],
	Esperanto: ['epo', 'eo'],
	Estonian: ['est', 'et'],
	Faroese: ['fao', 'fo'],
	'Filipino; Pilipino': ['fil'],
	Finnish: ['fin', 'fi'],
	'Finno-Ugrian languages': ['fiu'],
	French: ['fre', 'fra', 'fr'],
	'French, Middle (ca.1400-1600)': ['frm'],
	'French, Old (842-ca.1400)': ['fro'],
	'Northern Frisian': ['frr'],
	'Eastern Frisian': ['frs'],
	'Western Frisian': ['fry', 'fy'],
	Friulian: ['fur'],
	'Germanic languages': ['gem'],
	Georgian: ['geo', 'kat', 'ka'],
	German: ['ger', 'deu', 'de'],
	Gilbertese: ['gil'],
	'Gaelic; Scottish Gaelic': ['gla', 'gd'],
	Irish: ['gle', 'ga'],
	Galician: ['glg', 'gl'],
	Manx: ['glv', 'gv'],
	'German, Middle High (ca.1050-1500)': ['gmh'],
	'German, Old High (ca.750-1050)': ['goh'],
	Gorontalo: ['gor'],
	Gothic: ['got'],
	'Greek, Ancient (to 1453)': ['grc'],
	'Greek, Modern (1453-)': ['gre', 'ell', 'el'],
	Guarani: ['grn', 'gn'],
	'Swiss German; Alemannic; Alsatian': ['gsw'],
	Gujarati: ['guj', 'gu'],
	"Gwich'in": ['gwi'],
	'Haitian; Haitian Creole': ['hat', 'ht'],
	Hawaiian: ['haw'],
	Hiligaynon: ['hil'],
	'Himachali languages; Western Pahari languages': ['him'],
	Hittite: ['hit'],
	'Hmong; Mong': ['hmn'],
	'Hiri Motu': ['hmo', 'ho'],
	Croatian: ['hrv', 'hr'],
	'Upper Sorbian': ['hsb'],
	Hungarian: ['hun', 'hu'],
	Icelandic: ['ice', 'isl', 'is'],
	'Sichuan Yi; Nuosu': ['iii', 'ii'],
	'Ijo languages': ['ijo'],
	Inuktitut: ['iku', 'iu'],
	'Interlingue; Occidental': ['ile', 'ie'],
	'Interlingua (International Auxiliary Language Association)': ['ina', 'ia'],
	'Indic languages': ['inc'],
	Indonesian: ['ind', 'id'],
	'Indo-European languages': ['ine'],
	Ingush: ['inh'],
	Inupiaq: ['ipk', 'ik'],
	'Iranian languages': ['ira'],
	'Iroquoian languages': ['iro'],
	Italian: ['ita', 'it'],
	Javanese: ['jav', 'jv'],
	Japanese: ['jpn', 'ja'],
	'Judeo-Persian': ['jpr'],
	'Judeo-Arabic': ['jrb'],
	'Kara-Kalpak': ['kaa'],
	'Kachin; Jingpho': ['kac'],
	'Kalaallisut; Greenlandic': ['kal', 'kl'],
	Kannada: ['kan', 'kn'],
	'Karen languages': ['kar'],
	Kashmiri: ['kas', 'ks'],
	Kabardian: ['kbd'],
	'Khoisan languages': ['khi'],
	'Central Khmer': ['khm', 'km'],
	'Khotanese; Sakan': ['kho'],
	'Kikuyu; Gikuyu': ['kik', 'ki'],
	Kinyarwanda: ['kin', 'rw'],
	'Kirghiz; Kyrgyz': ['kir', 'ky'],
	Kimbundu: ['kmb'],
	Konkani: ['kok'],
	Kosraean: ['kos'],
	'Karachay-Balkar': ['krc'],
	Karelian: ['krl'],
	'Kru languages': ['kro'],
	'Kuanyama; Kwanyama': ['kua', 'kj'],
	Kutenai: ['kut'],
	Ladino: ['lad'],
	Lezghian: ['lez'],
	'Limburgan; Limburger; Limburgish': ['lim', 'li'],
	Lingala: ['lin', 'ln'],
	Lithuanian: ['lit', 'lt'],
	'Luxembourgish; Letzeburgesch': ['ltz', 'lb'],
	'Luba-Lulua': ['lua'],
	'Luba-Katanga': ['lub', 'lu'],
	Luiseno: ['lui'],
	'Luo (Kenya and Tanzania)': ['luo'],
	Macedonian: ['mac', 'mkd', 'mk'],
	Madurese: ['mad'],
	Marshallese: ['mah', 'mh'],
	Maithili: ['mai'],
	Makasar: ['mak'],
	Malayalam: ['mal', 'ml'],
	Mandingo: ['man'],
	'Austronesian languages': ['map'],
	Marathi: ['mar', 'mr'],
	'Irish, Middle (900-1200)': ['mga'],
	"Mi'kmaq; Micmac": ['mic'],
	Minangkabau: ['min'],
	'Uncoded languages': ['mis'],
	'Mon-Khmer languages': ['mkh'],
	Malagasy: ['mlg', 'mg'],
	Maltese: ['mlt', 'mt'],
	Manchu: ['mnc'],
	Manipuri: ['mni'],
	'Manobo languages': ['mno'],
	Mongolian: ['mon', 'mn'],
	'Multiple languages': ['mul'],
	'Munda languages': ['mun'],
	Mirandese: ['mwl'],
	Marwari: ['mwr'],
	'Mayan languages': ['myn'],
	'Nahuatl languages': ['nah'],
	'North American Indian languages': ['nai'],
	Neapolitan: ['nap'],
	'Navajo; Navaho': ['nav', 'nv'],
	'Ndebele, South; South Ndebele': ['nbl', 'nr'],
	'Ndebele, North; North Ndebele': ['nde', 'nd'],
	'Low German; Low Saxon; German, Low; Saxon, Low': ['nds'],
	Nepali: ['nep', 'ne'],
	'Nepal Bhasa; Newari': ['new'],
	'Niger-Kordofanian languages': ['nic'],
	'Norwegian Nynorsk; Nynorsk, Norwegian': ['nno', 'nn'],
	'Bokmål, Norwegian; Norwegian Bokmål': ['nob', 'nb'],
	Nogai: ['nog'],
	'Norse, Old': ['non'],
	Norwegian: ['nor', 'no'],
	'Pedi; Sepedi; Northern Sotho': ['nso'],
	'Nubian languages': ['nub'],
	'Classical Newari; Old Newari; Classical Nepal Bhasa': ['nwc'],
	'Chichewa; Chewa; Nyanja': ['nya', 'ny'],
	Nyamwezi: ['nym'],
	Nyankole: ['nyn'],
	'Occitan (post 1500)': ['oci', 'oc'],
	'Ossetian; Ossetic': ['oss', 'os'],
	'Turkish, Ottoman (1500-1928)': ['ota'],
	'Otomian languages': ['oto'],
	'Papuan languages': ['paa'],
	Pangasinan: ['pag'],
	Pahlavi: ['pal'],
	'Pampanga; Kapampangan': ['pam'],
	'Panjabi; Punjabi': ['pan', 'pa'],
	Papiamento: ['pap'],
	'Persian, Old (ca.600-400 B.C.)': ['peo'],
	Persian: ['per', 'fas', 'fa'],
	'Philippine languages': ['phi'],
	Phoenician: ['phn'],
	Polish: ['pol', 'pl'],
	Pohnpeian: ['pon'],
	Portuguese: ['por', 'pt'],
	'Prakrit languages': ['pra'],
	'Provençal, Old (to 1500); Occitan, Old (to 1500)': ['pro'],
	'Pushto; Pashto': ['pus', 'ps'],
	'Reserved for local use': ['qaa-qtz'],
	Quechua: ['que', 'qu'],
	Rajasthani: ['raj'],
	Rapanui: ['rap'],
	'Rarotongan; Cook Islands Maori': ['rar'],
	'Romance languages': ['roa'],
	Romansh: ['roh', 'rm'],
	'Romanian; Moldavian; Moldovan': ['rum', 'ron', 'ro'],
	'Aromanian; Arumanian; Macedo-Romanian': ['rup'],
	Sandawe: ['sad'],
	'South American Indian languages': ['sai'],
	'Salishan languages': ['sal'],
	'Samaritan Aramaic': ['sam'],
	Sanskrit: ['san', 'sa'],
	Sicilian: ['scn'],
	Selkup: ['sel'],
	'Semitic languages': ['sem'],
	'Irish, Old (to 900)': ['sga'],
	'Sign Languages': ['sgn'],
	'Sinhala; Sinhalese': ['sin', 'si'],
	'Siouan languages': ['sio'],
	'Sino-Tibetan languages': ['sit'],
	'Slavic languages': ['sla'],
	Slovak: ['slo', 'slk', 'sk'],
	Slovenian: ['slv', 'sl'],
	'Southern Sami': ['sma'],
	'Northern Sami': ['sme', 'se'],
	'Sami languages': ['smi'],
	'Lule Sami': ['smj'],
	'Inari Sami': ['smn'],
	'Skolt Sami': ['sms'],
	Soninke: ['snk'],
	Sogdian: ['sog'],
	'Songhai languages': ['son'],
	'Sotho, Southern': ['sot', 'st'],
	'Spanish; Castilian': ['spa', 'es'],
	Sardinian: ['srd', 'sc'],
	'Sranan Tongo': ['srn'],
	'Nilo-Saharan languages': ['ssa'],
	Sundanese: ['sun', 'su'],
	Sumerian: ['sux'],
	Swahili: ['swa', 'sw'],
	Swedish: ['swe', 'sv'],
	'Classical Syriac': ['syc'],
	Syriac: ['syr'],
	Tahitian: ['tah', 'ty'],
	'Tai languages': ['tai'],
	Telugu: ['tel', 'te'],
	Tagalog: ['tgl', 'tl'],
	Tibetan: ['tib', 'bod', 'bo'],
	Tigrinya: ['tir', 'ti'],
	Tokelau: ['tkl'],
	'Klingon; tlhIngan-Hol': ['tlh'],
	Tlingit: ['tli'],
	Tamashek: ['tmh'],
	'Tonga (Nyasa)': ['tog'],
	'Tonga (Tonga Islands)': ['ton', 'to'],
	'Tok Pisin': ['tpi'],
	Tsimshian: ['tsi'],
	Turkmen: ['tuk', 'tk'],
	Tumbuka: ['tum'],
	'Tupi languages': ['tup'],
	'Altaic languages': ['tut'],
	Udmurt: ['udm'],
	Ugaritic: ['uga'],
	'Uighur; Uyghur': ['uig', 'ug'],
	Ukrainian: ['ukr', 'uk'],
	Umbundu: ['umb'],
	Undetermined: ['und'],
	Vietnamese: ['vie', 'vi'],
	Volapük: ['vol', 'vo'],
	'Wakashan languages': ['wak'],
	'Wolaitta; Wolaytta': ['wal'],
	'Sorbian languages': ['wen'],
	'Kalmyk; Oirat': ['xal'],
	Yiddish: ['yid', 'yi'],
	'Yupik languages': ['ypk'],
	Zapotec: ['zap'],
	'Blissymbols; Blissymbolics; Bliss': ['zbl'],
	'Standard Moroccan Tamazight': ['zgh'],
	'Zhuang; Chuang': ['zha', 'za'],
	'Zande languages': ['znd'],
	'No linguistic content; Not applicable': ['zxx'],
	'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki': ['zza'],
} as const;

export type LanguageName = keyof typeof languageCodes;
export type LanguageCode = (typeof languageCodes)[LanguageName][number];
